### ISSUE TITLE
Program crashes when trying to convert a .CUBE

### ISSUE THREAD

**Issue by NazzarenoGiannelli** [dvjvp/LUT-to-UE4-clut#1]
As title says, whenever I try to convert a .cube the application crashes and closes.

**Comment by redega** [comment]
+1

**Comment by dvjvp** [comment]
This issue should be fixed in the new version.
If it still exists, please attach LUT file which causes the crash.

**Comment by NazzarenoGiannelli** [comment]
tried the new version with different .cube. Not crashing but I don't see any .png created where I specify

**Comment by redega** [comment]
I hace crash after selecting output directory (before it was on convert button )

**Comment by NazzarenoGiannelli** [comment]
> I hace crash after selecting output directory (before it was on convert button )

Same here

**Comment by dvjvp** [comment]
If that's the case, I'd like to ask you to send me a LUT file you're trying to run conversion process on ('cause for the ones I'm using for testing, everything seems to be working).

**Comment by NazzarenoGiannelli** [comment]
every .cube I tried brought to the same result.
Here is one of them
[https://www.dropbox.com/s/ij98xkidx84uhcn/Adanmq_Advantix%20100.cube?dl=0](url)

**Comment by redega** [comment]
https://we.tl/t-NdjUUe5N4M
Maybe the problem not with .cube and with unzipping/antivirus?
Maybe you have installed some non-standard redistributables etc?
Just guessing:) WIN 10 x64 ltsb

**Comment by NazzarenoGiannelli** [comment]
Nothing fancy or strange installed.
No antivirus here, just regular Windows Defender

Do I need to install something in particular in order to make it work?
Do i need to run something else that is not the .exe that comes with the repository?

**Comment by dvjvp** [comment]
The problem was definiently with the *.cube file, it was created in a valid format, but slightly different to one I was using.
You don't need to install anything, just running the .exe should be enough to make it work.
I commited updated version, I believe it should work now.

**Comment by NazzarenoGiannelli** [comment]
ahah nice commit comment
Tried and works perfectly!
Thank you so much!
